### ISSUE TITLE
Multi thread solution

### ISSUE THREAD

**Issue by NormanBB** [MrLutik/KiraScan#1]
I wrote another version base on yours.

[Kirascan](https://github.com/NormanBB/KiraScan)

This is just a demo.I just want to reduce time so i don't consider so much thing such as OOP ,  more heads up or print more things.

We all know ping is not a good solution right now, what's your opinion?

I hope this may help you. :)

`Time reduced from 800+ s to 80+s.`

**Comment by MrLutik** [comment]
@NormanBB that's a good point. Will improve it. tag you when finished.

**Comment by NormanBB** [comment]
I suggest provide single usable ip in the beginning is main goal in this period.Because it can help people set up a validator quickly and ignore annoying stuff.No need to enter advanced mode.I think it confuses people not familiar with testnet.

To do this,i am thinking imitate [kira script](https://github.com/KiraCore/kira/blob/testnet-3/workstation/menu/quick-select.sh).

Test download `68.168.223.144:11000/download/snapshot.zip`. Check status code.

Just my opinion, i will now continue to write script right now.

**Comment by MrLutik** [comment]
@NormanBB what you need is just a simple parser. Resource with ips containing snaps is publicly available:

[Ip with snaps](https://testnet-rpc.kira.network/download/snaps.txt)

**Comment by NormanBB** [comment]
All right, thanks for your opinion.

**Comment by NormanBB** [comment]
There is another typo.

![Screenshot from 2021-05-17 07-47-15](https://user-images.githubusercontent.com/18748504/118416843-28e7a300-b6e4-11eb-98ef-70a1471f3e17.png)

paste instead of past.
